change to navigation controller
MikeBarannikov/FragmentNavigation pull request #1
Opened 2018-05-17 22:10 UTC by dkonurov

2018-05-18 04:37 UTC, MikeBarannikov commented
Каждая навигация идет в отдельную ветку, а не в мастер.

2018-05-21 07:17 UTC, dkonurov commented
поправил

2018-05-26 04:17 UTC, MikeBarannikov requested changes

2018-05-26 04:17 UTC, MikeBarannikov commented on app/src/main/java/com/crazy/fragmentnavigation/ui/base/BaseViewPagerFragment.java
> +public abstract class BaseViewPagerFragment extends NavHostFragment {
Отнаследоваться от BaseNavHostFragment?

2019-09-10 05:38 UTC, merged